version: '3'
services:
  rambutan:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always
    environment:
      - FLASK_ENV=production
    command: ["gunicorn", "-c", "/etc/default/gunicorn", "apps:create_app()"]
