apiVersion: v1
kind: Service
metadata:
  name: rambutan
  namespace: v
  labels:
    app: rambutan
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: rambutan
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rambutan
  namespace: v
spec:
  selector:
    matchLabels:
      app: rambutan
  replicas: 1
  template:
    metadata:
      labels:
        app: rambutan
    spec:
      containers:
      - image: epub-registry.cn-hangzhou.cr.aliyuncs.com/21epub/rambutan:1.2.9
        imagePullPolicy: Always
        name: rambutan
        command: ["gunicorn", "-c", "/etc/default/gunicorn.py", "apps:create_app()"]
        env:
        - name: DATE
        - name: FLASK_ENV
          value: production
        - name: STORAGE_TYPE
          value: oss
        - name: STORAGE_PATH
          value: ""
        - name: OSS_BUCKET_NAME
          value: "epub360-media"
        - name: OSS_ENDPOINT
          value: "oss-cn-hangzhou.aliyuncs.com"
        - name: OSS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: rambutan-secret
              key: access-key-id
        - name: OSS_ACCESS_KEY_SECRET
          valueFrom:
            secretKeyRef:
              name: rambutan-secret
              key: access-key-secret
        resources:
          requests:
            cpu: "200m"
      imagePullSecrets:
        - name: cr-reg
        - name: cri-reg

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rambutan
  namespace: v
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "180"
spec:
  ingressClassName: nginx
  rules:
  - host: v.epub360.com
    http:
      paths:
      - path: /epub360-media/
        pathType: Prefix
        backend:
          service:
            name: rambutan
            port:
              number: 8000
